version: 2
project_name: fscli
env:
  - GO111MODULE=on
builds:
  - main: ./cmd/fscli
    binary: fscli
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
brews:
  - repository:
      owner: maruware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/maruware/fscli"
    description: "A cli tool for firestore"
    license: "MIT"
    install: |
      bin.install "fscli"
