project_name: fscli
env:
  - GO111MODULE=on
builds:
  - main: ./cmd/fscli
    binary: fscli
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
