name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: 2023.1.6
          install-go: false

      - name: up firestore
        run: docker compose up -d --wait
        working-directory: ./local

      - name: Test
        run: go test -v ./...

      - name: down firestore
        run: docker compose down
        working-directory: ./local
