name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -v ./...

      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: 2025.1.1
          install-go: false

      - name: up firestore
        run: docker compose up -d --wait
        working-directory: ./local

      - name: Test
        run: go test -v ./...

      - name: down firestore
        run: docker compose down
        working-directory: ./local
